### ISSUE TITLE
为什么我这样初始化，会报错

### ISSUE THREAD

**Issue by astak16** [antvis/SAMJS#19]
```js
const WasmPaths = "https://npm.elemecdn.com/onnxruntime-web/dist/";
const sam = new SAMGeo({
  // modelUrl: MODEL_URL,
  wasmPaths: WasmPaths,
});
await sam.initModel();
```
![image](https://github.com/antvis/SAMJS/assets/35784058/d5fa946c-71f7-49a1-8702-75baccf6d075)
![image](https://github.com/antvis/SAMJS/assets/35784058/6559d51b-bfa0-46a7-8799-b58087a54023)

**Comment by lzxue** [comment]
新版版本已修复
