### ISSUE TITLE
初始化失败 版本 为"@antv/sam": "^0.1.0",

### ISSUE THREAD

**Issue by chwang9** [antvis/SAMJS#24]
`  const samGeoModel = new SAMGeo({
    modelUrl: MODEL_URL, // antv/sam 提供的了默认的 onnx 服务
  });
`
`  samGeoModel.initModel().then(() => {
    // do something
  });`
![image](https://github.com/antvis/SAMJS/assets/45502878/c6809ef2-2d29-43b3-b674-33a80d9dfdc0)

**Comment by rehan-focusteck** [comment]
Same Issue I have found and stucked on it.
<img width="608" alt="modal-loading-error" src="https://github.com/antvis/SAMJS/assets/135612429/6a70f502-3f87-4bbf-a77a-dbf9cc64c0ca">

**Comment by chwang9** [comment]
![image](https://github.com/antvis/SAMJS/assets/45502878/49f046ed-e66d-492d-bfea-e9aff90d493
这样可以，不报错

**Comment by chwang9** [comment]
![image](https://github.com/antvis/SAMJS/assets/45502878/632f85fa-df79-4d0c-87e6-bf3150923b4c)

**Comment by rehan-focusteck** [comment]
> ![image](https://user-images.githubusercontent.com/45502878/256389394-632f85fa-df79-4d0c-87e6-bf3150923b4c.png)

I didn't get your point, whats purpose of this screenshot?

**Comment by chwang9** [comment]
找到这个文件，放到这个目录下面（vue项目），项目就可以运行了

**Comment by lzxue** [comment]
或者通过 Webpack 来配置。

```ts
plugins: [
  new CopyPlugin({
    patterns: [
      {
        from: 'node_modules/onnxruntime-web/dist/*.wasm',
        to: '[name][ext]',
      },
      {
        from: 'model',
        to: 'model',
      },
      {
        from: 'src/assets',
        to: 'assets',
      },
    ],
  }),
];
```

**Comment by lzxue** [comment]
re #34
