### ISSUE TITLE
exportGeoPolygon方法导出的多边形不准确

### ISSUE THREAD

**Issue by znxd-wh** [antvis/SAMJS#31]
当分割的多边形是个复杂地物的时候，如下图所示
![image](https://github.com/antvis/SAMJS/assets/42760174/db26948d-5e2c-4316-8018-69fff0d01cdf)
但exportGeoPolygon导出的矢量如下
![image](https://github.com/antvis/SAMJS/assets/42760174/3318db6f-6dfd-479d-8eab-90734bec98f7)
只有3个点，完全匹配不上
请问还有其他什么参数设置吗？

**Comment by znxd-wh** [comment]
追加一下问题描述，如果是多点进行predict的话，如果结果是一个polygon，那么exportGeoPolygon的结果没有问题，如果结果是个multipolygon的话，exportGeoPolygon的结果就不正确了。如下图所示，predict的points和结果的geojson矢量
![image](https://github.com/antvis/SAMJS/assets/42760174/542c3613-a0ca-42be-80f1-a728d0ff23b4)
但用exportImageClip方法导出的图片是正确的
![image](https://github.com/antvis/SAMJS/assets/42760174/89bb044b-08d0-4a2a-ae7b-a176ea52ac3b)

**Comment by lzxue** [comment]
是不太准确，栅格转矢量算法的问题

**Comment by lzxue** [comment]
你这个是自己实现的吗？

**Comment by znxd-wh** [comment]
我就是把L7换成了ol，其他用的都是SAMJS。我想请教一下，SAMJS是完全基于meta的segment-anything项目做的吗？有没有参考segment-geospatial项目？git地址：https://github.com/opengeos/segment-geospatial
segment-geospatial里面分割的矢量是准确的，不过矢量也都是polygon，没有复杂的情况，比如hole或者multi的情况没有，下图是segment-geospatial分割的矢量结果，叠加到tif上
![微信图片_20230908104921](https://github.com/antvis/SAMJS/assets/42760174/ea146271-02f7-46d8-a56e-94f07facc55d)
samjs源码没有仔细看，如果是用raster转vector出的问题的话，这块我可以尝试解决一下，有进展的话我会fork一个项目到我的git中，进行更新，如果您觉得有贡献的话可以合并到主库中

**Comment by astak16** [comment]
> 我就是把L7换成了ol，其他用的都是SAMJS。我想请教一下，SAMJS是完全基于meta的segment-anything项目做的吗？有没有参考segment-geospatial项目？git地址：https://github.com/opengeos/segment-geospatial segment-geospatial里面分割的矢量是准确的，不过矢量也都是polygon，没有复杂的情况，比如hole或者multi的情况没有，下图是segment-geospatial分割的矢量结果，叠加到tif上 ![微信图片_20230908104921](https://user-images.githubusercontent.com/42760174/266489173-ea146271-02f7-46d8-a56e-94f07facc55d.png) samjs源码没有仔细看，如果是用raster转vector出的问题的话，这块我可以尝试解决一下，有进展的话我会fork一个项目到我的git中，进行更新，如果您觉得有贡献的话可以合并到主库中

有进展不😁

**Comment by lzxue** [comment]
> https://github.com/opengeos/segment-geospatial

没有 SamJS 是纯前端的，segment-geospatial 应该是服务端转做的raster2vector python 生态比较成熟。SAMJS 的ratser2vector 是自己实现的
