### ISSUE TITLE
模型加载失败

### ISSUE THREAD

**Issue by feifeirun97** [antvis/SAMJS#34]
![image](https://github.com/antvis/SAMJS/assets/61611167/997522ab-2d2b-4484-a85e-0f481c87290d)

<img width="997" alt="image" src="https://github.com/antvis/SAMJS/assets/61611167/9d5772e3-c67a-472e-ab54-7d00fc89ea0b">
<img width="509" alt="image" src="https://github.com/antvis/SAMJS/assets/61611167/e5806248-a4eb-4dfc-a868-96290b0c9ebc">

**Comment by lzxue** [comment]
```ts
plugins: [
  new CopyPlugin({
    patterns: [
      {
        from: 'node_modules/onnxruntime-web/dist/*.wasm',
        to: '[name][ext]',
      }
    ],
  }),
];
```
需要配置一下 wasm
